[project]
name = "09-rag-app-using-pinecone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pinecone-haystack>=5.2.0",
]
