# Changes here will be overwritten by Copier
_commit: 2024.11.28
_src_path: gh:zenml-io/template-starter
email: l.michalik004@gmail.com
full_name: ZenML GmbH
open_source_license: apache
project_name: ZenML Starter
version: 0.1.0
